### ISSUE TITLE
Channel Launch

### ISSUE THREAD

**Issue by atymic** [laravel-notification-channels/turbosms#1]
- [x] Code Review
- [x] Add @gvital3230 as repo admin
- [x] Add @gvital3230 to github org
- [ ] Add to website
- [x] Create packagist package
- [x] Travis
- [x] Style CI
- [x] Scrutinizer 
- [x] Add badges

**Comment by atymic** [comment]
Website PR is here: https://github.com/laravel-notification-channels/website/pull/17

Ready to merge, @gvital3230 could you please tag the first release when you are ready :)

**Comment by gvital3230** [comment]
Thank you. Done.

**Comment by atymic** [comment]
Website PR merged :)
